version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - frontend


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development


  db:
    image: postgres:13  # Official PostgreSQL image
    environment:
      POSTGRES_USER: user  # Username for DB connection
      POSTGRES_PASSWORD: password  # Password for DB connection
      POSTGRES_DB: mydb  # Name of the database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist DB data
    ports:
      - "5432:5432"  # Expose DB port if needed for testing
    networks:
      - web-chat

networks:
  web-chat:
    driver: bridge

volumes:
  postgres_data: {}  # Volumes for persisting data across container restarts