version: "3.8"

services:
  backend:
    image: saidsmajicwork/backend:latest   # Use your Docker Hub image here
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - frontend
    networks:
      - web-chat

  frontend:
    image: saidsmajicwork/frontend:latest   # Use your Docker Hub image here
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web-chat

networks:
  web-chat:
    driver: bridge
