version: "3.8"

services:
  backend:
    image: saidsmajicwork/backend:latest   # Use your Docker Hub image here
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
    networks:
      - web-chat

  frontend:
    image: saidsmajicwork/frontend:latest   # Use your Docker Hub image here
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - web-chat

networks:
  web-chat:
    driver: bridge
