version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:                  # Load environment variables from backend/.env
      - ./backend/.env
    depends_on:
      - frontend
    networks:
      - web-chat

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - web-chat

networks:
  web-chat:
    driver: bridge
