name: Deploy to Contabo

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Login to Docker
          run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Build and Push Backend Image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

        - name: Build and Push Frontend Image
          run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

        - name: Deploy on Contabo VPS
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: |
                # Check if the repository exists on VPS, otherwise clone it
                if [ ! -d "/home/${{ secrets.SSH_USER }}/repo" ]; then
                  git clone https://github.com/${{ secrets.GITHUB_REPOSITORY }} /home/${{ secrets.SSH_USER }}/repo
                fi

                # Navigate to repo directory
                cd /home/${{ secrets.SSH_USER }}/repo

                # Pull the latest changes
                git pull origin main

                # Login to Docker Hub
                docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

                # Pull the latest backend and frontend images
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

                # Use Docker Compose to restart the containers
                docker-compose down
                docker-compose up -d --force-recreate

                # Clean up unused Docker images
                docker image prune -af
