name: Deploy to Contabo

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Login to Docker
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Step 3: Build and Push Backend Image
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

    # Step 4: Build and Push Frontend Image
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    # Step 5: Deploy on Contabo VPS
    - name: Deploy on Contabo VPS
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Check if the repository exists on VPS, otherwise clone it
          if [ ! -d "/home/${{ secrets.SSH_USER }}/repo" ]; then
            git clone https://github.com/${{ secrets.GITHUB_REPOSITORY }} /home/${{ secrets.SSH_USER }}/repo
          fi

          # Navigate to repo directory
          cd /home/${{ secrets.SSH_USER }}/repo

          # Pull the latest changes from GitHub repository
          git pull origin main

          # Login to Docker Hub
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

          # Pull the latest backend and frontend images
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

          # Use Docker Compose to restart the containers
          docker-compose down
          docker-compose up -d --force-recreate

          # Clean up unused Docker images
          docker image prune -af
